#!/bin/bash
ADDJOVIANDSSPATCH=$(cat <<'END'
***************
*** 30,35 ****
--- 30,36 ----
  );

  our @SHARED_STORAGE = (
+     'joviandss',
      'iscsi',
      'nfs',
      'cifs',
END
)

echo "$ADDJOVIANDSSPATCH" | patch -R /usr/share/perl5/PVE/Storage/Plugin.pm

exit 0
